name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Archive
        uses: devbotsxyz/xcode-archive@v1

      - name: Setup Jellyfin server
        run: |
          curl -L -o jellyfin.tar.gz https://repo.jellyfin.org/releases/server/macos/stable-pre/10.8.0-beta2/combined/jellyfin_10.8.0-beta2.tar.gz
          tar -xf jellyfin.tar.gz
          # move Jellyfin server
          mv jellyfin_*/* Jellyfin\ Server.xcarchive/Products/Applications/Jellyfin\ Server.app/Contents/MacOS
          # move Jellyfin web
          mv Jellyfin\ Server.xcarchive/Products/Applications/Jellyfin\ Server.app/Contents/MacOS/jellyfin-web Jellyfin\ Server.xcarchive/Products/Applications/Jellyfin\ Server.app/Contents/Resources

      - name: Setup ffmpeg
        run: |
          curl -L -o ffmpeg.zip https://evermeet.cx/pub/ffmpeg/ffmpeg-4.4.1.zip
          unzip ffmpeg.zip
          mv ffmpeg Jellyfin\ Server.xcarchive/Products/Applications/Jellyfin\ Server.app/Contents/MacOS
          
      - name: Setup ffprobe
        run: |
          curl -L -o ffprobe.zip https://evermeet.cx/pub/ffprobe/ffprobe-4.4.1.zip
          unzip ffprobe.zip
          mv ffprobe Jellyfin\ Server.xcarchive/Products/Applications/Jellyfin\ Server.app/Contents/MacOS          

      - name: Export
        uses: devbotsxyz/xcode-export-archive@v1.0.0

      - name: List
        run: |
          ls -l ./Export