name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Build
        uses: devbotsxyz/xcode-archive@v1
        
      - name: List
        run: |
          ls -la